import { AppStoreConnectProvider } from "./providers/app-store-connect-provider.mjs";
import { SearchConsoleProvider } from "./providers/search-console-provider.mjs";
import { ProviderAuthRequiredError } from "./providers/contracts.mjs";
import { ATTRIBUTION_CONFIDENCE, PROVIDER_SLAS, attributionConfidence, classifyReviews, detectSearchOpportunities, ingestMetrics, ingestReviews, ingestSearch, instrumentationMaturity, providerFreshness, reconcileMetrics, reviewOpportunities } from "./growth-data.mjs";

const isoDate=(date)=>date.toISOString().slice(0,10);
const daysBefore=(date,days)=>{const copy=new Date(date);copy.setUTCDate(copy.getUTCDate()-days);return copy;};
const errorSummary=(error)=>({code:error.code??"PROVIDER_ERROR",message:error.code==="REPORT_REQUEST_REQUIRED"?"BLOCKED — ONE-TIME ADMIN ANALYTICS REPORT REQUEST REQUIRED":error.message?.includes("AUTH REQUIRED")?"BLOCKED — AUTH REQUIRED":"Provider sync failed; previous verified data retained.",retryable:Boolean(error.retryable),required_configuration:error instanceof ProviderAuthRequiredError?error.missing:[]});

function audit(state,{at,action,result,status="success"}){state.audit.unshift({id:crypto.randomUUID(),at,actor:"AI COO OS",app_id:"style-atlas",source:"phase_3_growth_cycle",action,input:{external_writes:false},result,status,error:null});}
function provider(state,id){return state.providers.find((row)=>row.id===id);}
function updateProvider(state,id,patch){const row=provider(state,id);if(row)Object.assign(row,patch);}

async function runSync(state,{id,appId,now,periodStart,periodEnd,operation,ingest,dataThroughOf}){
  const startedAt=now.toISOString();const sync={id:`sync-${id}-${startedAt.replace(/[:.]/g,"-")}`,app_id:appId,provider:id,period_start:periodStart,period_end:periodEnd,started_at:startedAt,completed_at:null,status:"running",records_received:0,records_inserted:0,records_updated:0,records_unchanged:0,data_through:null,error:null};state.provider_syncs.push(sync);
  try{const result=await operation();const counts=ingest(result);Object.assign(sync,{completed_at:new Date().toISOString(),status:"succeeded",records_received:counts.received,records_inserted:counts.inserted,records_updated:counts.updated,records_unchanged:counts.unchanged,data_through:dataThroughOf(result)});return sync;}
  catch(error){const safe=errorSummary(error);Object.assign(sync,{completed_at:new Date().toISOString(),status:["AUTH_REQUIRED","REPORT_REQUEST_REQUIRED"].includes(safe.code)?"blocked":"failed",error:safe});return sync;}
}

function updateScheduledJob(state,sync,now){
  const job=state.jobs.find((row)=>row.provider===sync.provider);if(!job)return;
  const succeeded=sync.status==="succeeded";Object.assign(job,{last_run:sync.completed_at,status:succeeded?"scheduled":sync.status,result:succeeded?{records_received:sync.records_received,records_inserted:sync.records_inserted,records_updated:sync.records_updated,data_through:sync.data_through}:null,error:sync.error?.message??null,next_run:succeeded?new Date(now.getTime()+86_400_000).toISOString():null,retry_count:sync.status==="failed"?(job.retry_count??0)+1:job.retry_count??0});
}

export async function runGrowthDataCycle(state,{appId="style-atlas",now=new Date(),appStoreProvider=new AppStoreConnectProvider(),searchProvider=new SearchConsoleProvider()}={}){
  const at=now.toISOString(),periodEnd=isoDate(daysBefore(now,1)),periodStart=isoDate(daysBefore(now,28));
  const ascHealth=await appStoreProvider.health(),gscHealth=await searchProvider.health();
  const asc=await runSync(state,{id:"app_store_connect_api",appId,now,periodStart,periodEnd,operation:async()=>{if(ascHealth.status==="blocked")throw new ProviderAuthRequiredError("app_store_connect_api",ascHealth.missing);return appStoreProvider.fetchAnalytics({appId,now:at});},ingest:(result)=>ingestMetrics(state,result.observations),dataThroughOf:(result)=>result.data_through});
  const reviews=await runSync(state,{id:"app_store_reviews_api",appId,now,periodStart:null,periodEnd,operation:async()=>{if(ascHealth.status==="blocked")throw new ProviderAuthRequiredError("app_store_reviews_api",ascHealth.missing);const observations=await appStoreProvider.fetchReviews({now:at});return{observations,data_through:periodEnd,verified_no_reviews:observations.length===0};},ingest:(result)=>ingestReviews(state,classifyReviews(result.observations)),dataThroughOf:(result)=>result.data_through});
  const search=await runSync(state,{id:"google_search_console_api",appId,now,periodStart,periodEnd,operation:async()=>{if(gscHealth.status==="blocked")throw new ProviderAuthRequiredError("google_search_console_api",gscHealth.missing);return searchProvider.fetchPerformance({appId,startDate:periodStart,endDate:periodEnd,now:at});},ingest:(result)=>ingestSearch(state,result.observations),dataThroughOf:(result)=>result.data_through});
  for(const sync of [asc,reviews,search]){const sla=PROVIDER_SLAS[sync.provider];const freshness=providerFreshness({dataThrough:sync.data_through,status:sync.status==="blocked"?"blocked":sync.status==="failed"?"stale":"connected",now,sla});const verifiedNoReviews=sync.provider==="app_store_reviews_api"&&sync.status==="succeeded"&&sync.records_received===0;updateProvider(state,sync.provider,{status:verifiedNoReviews?"verified_no_reviews":sync.status==="succeeded"?"available":sync.status,last_sync:sync.completed_at,last_successful_import:sync.status==="succeeded"?sync.completed_at:provider(state,sync.provider)?.last_successful_import??null,data_through:sync.data_through??provider(state,sync.provider)?.data_through??null,freshness:freshness.status,authentication_required:sync.status==="blocked",authentication_status:sync.status==="blocked"?"not_configured":"configured",error:sync.error?.message??null,required_configuration:sync.error?.required_configuration??[]});updateScheduledJob(state,sync,now);}
  const reconciliation=reconcileMetrics(state,{appId});
  const searchRows=state.search_observations.filter((row)=>row.app_id===appId);const searchOpportunities=detectSearchOpportunities(searchRows);
  const reviewRows=state.feedback.filter((row)=>row.app_id===appId&&row.provider==="app_store_reviews_api");const vocOpportunities=reviewOpportunities(reviewRows);
  state.opportunities=state.opportunities.filter((row)=>!String(row.id).startsWith("search-opportunity-")&&!String(row.id).startsWith("review-opportunity-"));
  state.opportunities.push(...searchOpportunities.map((row)=>({id:`search-opportunity-${crypto.randomUUID()}`,app_id:appId,status:"open",verification_type:"calculated",...row})),...vocOpportunities);
  for(const row of state.attributions){row.confidence_class=ATTRIBUTION_CONFIDENCE.includes(row.confidence_class)?row.confidence_class:attributionConfidence(row);}
  state.instrumentation=state.apps.map((app)=>({id:`instrumentation-${app.id}`,app_id:app.id,level:instrumentationMaturity(state,app.id),updated_at:at,source:"calculated_from_verified_coverage"}));
  const dataThrough={app_store:asc.data_through??null,app_store_reviews:reviews.data_through??null,search_console:search.data_through??null,manual_app_store:state.metrics.filter((row)=>row.app_id===appId&&row.verification_type==="manual_verified").map((row)=>row.period_end).sort().at(-1)??null};state.metadata.data_through=dataThrough;state.metadata.last_growth_cycle_at=at;
  const syncs=[asc,reviews,search],blocked=syncs.filter((row)=>row.status==="blocked").length,failed=syncs.filter((row)=>row.status==="failed").length,succeeded=syncs.filter((row)=>row.status==="succeeded").length;
  const cycle={id:`growth-cycle-${appId}-${at.replace(/[:.]/g,"-")}`,app_id:appId,version:"v2",started_at:at,completed_at:new Date().toISOString(),status:succeeded===0&&blocked===syncs.length?"blocked":failed||blocked?"partial":"completed",stages:{sync:{succeeded,blocked,failed,provider_sync_ids:syncs.map((row)=>row.id)},validate:{status:"completed",invalid_records:0},reconcile:{status:"completed",...reconciliation},detect:{status:"completed",search_opportunities:searchOpportunities.length,review_opportunities:vocOpportunities.length},brief:{status:"completed",data_through:dataThrough},approve:{status:"not_required",risk_level:0},execute:{status:"completed",action:"Refresh internal growth-data readiness and reconciliation."},measure:{status:"completed",new_conclusive_outcomes:0},learn:{status:"completed",new_learnings:0}},detected:{result:searchOpportunities.length||vocOpportunities.length?"Evidence-backed opportunities detected.":"No material change detected.",material_changes:searchOpportunities.length+vocOpportunities.length},decided:{decision:blocked?"Connect the minimum read-only credentials; retain verified baseline until then.":"Continue measurement-first daily sync."},data_through:dataThrough};state.cycles.push(cycle);
  audit(state,{at,action:"run_growth_data_cycle_v2",result:{cycle_id:cycle.id,status:cycle.status,provider_syncs:{succeeded,blocked,failed},reconciliation,search_opportunities:searchOpportunities.length,review_opportunities:vocOpportunities.length,data_through:dataThrough},status:cycle.status==="completed"?"success":"blocked"});
  return {cycle,syncs,reconciliation,search_opportunities:searchOpportunities,voc_opportunities:vocOpportunities};
}
